using System.Collections;
using System.Collections.Generic;
using UnityEngine;
public class SavedSceneGenerator : MonoBehaviour {
public Texture m_MainTexture, m_Normal;
Renderer m_Renderer;
void Update() { 
if(Input.GetKeyDown(KeyCode.J)) {loadScene();}}
public static void loadScene() {
Object[] allObjects = Resources.FindObjectsOfTypeAll(typeof(GameObject));
foreach (GameObject o in allObjects)
{
if (o.name.StartsWith("building") || o.name.StartsWith("Landmark") || o.name.StartsWith("park") || o.name.StartsWith("Pavement"))
{
Destroy(o);
}}
GameObject obj_1 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_1.name = "building_0_0";
 obj_1.transform.localScale = new Vector3(3, 17, 4);
 obj_1.transform.position = new Vector3(-100, 9, -100);
 obj_1.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_1.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_1.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_1.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_1.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_2 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_2.name = "building_0_4";
 obj_2.transform.localScale = new Vector3(2, 19, 3);
 obj_2.transform.position = new Vector3(-100, 10, -84);
 obj_2.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_2.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_2.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_2.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_2.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_3 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_3.name = "building_0_8";
 obj_3.transform.localScale = new Vector3(1, 12, 2);
 obj_3.transform.position = new Vector3(-100, 6, -68);
 obj_3.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_3.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_3.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_3.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_3.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_4 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_4.name = "building_0_12";
 obj_4.transform.localScale = new Vector3(3, 18, 1);
 obj_4.transform.position = new Vector3(-100, 9, -52);
 obj_4.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_4.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_4.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_4.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_4.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_5 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_5.name = "building_0_16";
 obj_5.transform.localScale = new Vector3(3, 10, 1);
 obj_5.transform.position = new Vector3(-100, 5, -36);
 obj_5.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_5.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_5.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_5.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_5.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_6 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_6.name = "building_0_20";
 obj_6.transform.localScale = new Vector3(1, 16, 2);
 obj_6.transform.position = new Vector3(-100, 8, -20);
 obj_6.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_6.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_6.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_6.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_6.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_7 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_7.name = "building_0_24";
 obj_7.transform.localScale = new Vector3(2, 13, 2);
 obj_7.transform.position = new Vector3(-100, 7, -4);
 obj_7.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_7.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_7.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_7.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_7.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_8 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_8.name = "building_0_28";
 obj_8.transform.localScale = new Vector3(4, 13, 4);
 obj_8.transform.position = new Vector3(-100, 7, 12);
 obj_8.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_8.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_8.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_8.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_8.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_9 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_9.name = "building_0_32";
 obj_9.transform.localScale = new Vector3(4, 19, 4);
 obj_9.transform.position = new Vector3(-100, 10, 28);
 obj_9.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_9.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_9.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_9.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_9.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_10 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_10.name = "building_0_36";
 obj_10.transform.localScale = new Vector3(1, 19, 3);
 obj_10.transform.position = new Vector3(-100, 10, 44);
 obj_10.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_10.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_10.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_10.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_10.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_11 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_11.name = "building_4_0";
 obj_11.transform.localScale = new Vector3(3, 19, 3);
 obj_11.transform.position = new Vector3(-84, 10, -100);
 obj_11.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_11.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_11.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_11.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_11.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_12 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_12.name = "building_4_4";
 obj_12.transform.localScale = new Vector3(1, 14, 2);
 obj_12.transform.position = new Vector3(-84, 7, -84);
 obj_12.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_12.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_12.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_12.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_12.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_13 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_13.name = "building_4_8";
 obj_13.transform.localScale = new Vector3(2, 19, 1);
 obj_13.transform.position = new Vector3(-84, 10, -68);
 obj_13.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_13.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_13.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_13.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_13.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_14 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_14.name = "building_4_12";
 obj_14.transform.localScale = new Vector3(3, 18, 4);
 obj_14.transform.position = new Vector3(-84, 9, -52);
 obj_14.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_14.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_14.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_14.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_14.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_15 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_15.name = "building_4_16";
 obj_15.transform.localScale = new Vector3(2, 19, 1);
 obj_15.transform.position = new Vector3(-84, 10, -36);
 obj_15.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_15.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_15.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_15.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_15.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_16 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_16.name = "building_4_20";
 obj_16.transform.localScale = new Vector3(3, 12, 3);
 obj_16.transform.position = new Vector3(-84, 6, -20);
 obj_16.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_16.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_16.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_16.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_16.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_17 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_17.name = "building_4_24";
 obj_17.transform.localScale = new Vector3(3, 16, 4);
 obj_17.transform.position = new Vector3(-84, 8, -4);
 obj_17.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_17.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_17.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_17.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_17.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_18 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_18.name = "building_4_28";
 obj_18.transform.localScale = new Vector3(2, 13, 1);
 obj_18.transform.position = new Vector3(-84, 7, 12);
 obj_18.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_18.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_18.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_18.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_18.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_19 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_19.name = "building_4_32";
 obj_19.transform.localScale = new Vector3(1, 18, 2);
 obj_19.transform.position = new Vector3(-84, 9, 28);
 obj_19.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_19.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_19.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_19.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_19.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_20 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_20.name = "building_4_36";
 obj_20.transform.localScale = new Vector3(4, 15, 4);
 obj_20.transform.position = new Vector3(-84, 8, 44);
 obj_20.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_20.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_20.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_20.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_20.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_21 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_21.name = "building_8_0";
 obj_21.transform.localScale = new Vector3(4, 10, 2);
 obj_21.transform.position = new Vector3(-68, 5, -100);
 obj_21.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_21.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_21.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_21.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_21.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_22 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_22.name = "building_8_4";
 obj_22.transform.localScale = new Vector3(3, 19, 4);
 obj_22.transform.position = new Vector3(-68, 10, -84);
 obj_22.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_22.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_22.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_22.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_22.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_23 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_23.name = "building_8_8";
 obj_23.transform.localScale = new Vector3(2, 15, 3);
 obj_23.transform.position = new Vector3(-68, 8, -68);
 obj_23.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_23.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_23.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_23.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_23.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_24 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_24.name = "building_8_12";
 obj_24.transform.localScale = new Vector3(4, 17, 3);
 obj_24.transform.position = new Vector3(-68, 9, -52);
 obj_24.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_24.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_24.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_24.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_24.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_25 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_25.name = "building_8_16";
 obj_25.transform.localScale = new Vector3(1, 18, 2);
 obj_25.transform.position = new Vector3(-68, 9, -36);
 obj_25.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_25.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_25.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_25.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_25.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_26 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_26.name = "building_8_20";
 obj_26.transform.localScale = new Vector3(2, 13, 2);
 obj_26.transform.position = new Vector3(-68, 7, -20);
 obj_26.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_26.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_26.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_26.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_26.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_27 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_27.name = "building_8_24";
 obj_27.transform.localScale = new Vector3(4, 12, 3);
 obj_27.transform.position = new Vector3(-68, 6, -4);
 obj_27.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_27.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_27.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_27.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_27.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_28 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_28.name = "building_8_28";
 obj_28.transform.localScale = new Vector3(2, 14, 2);
 obj_28.transform.position = new Vector3(-68, 7, 12);
 obj_28.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_28.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_28.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_28.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_28.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_29 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_29.name = "building_8_32";
 obj_29.transform.localScale = new Vector3(4, 11, 3);
 obj_29.transform.position = new Vector3(-68, 6, 28);
 obj_29.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_29.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_29.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_29.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_29.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_30 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_30.name = "building_8_36";
 obj_30.transform.localScale = new Vector3(3, 18, 3);
 obj_30.transform.position = new Vector3(-68, 9, 44);
 obj_30.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_30.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_30.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_30.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_30.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_31 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_31.name = "building_12_0";
 obj_31.transform.localScale = new Vector3(4, 14, 2);
 obj_31.transform.position = new Vector3(-52, 7, -100);
 obj_31.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_31.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_31.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_31.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_31.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_32 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_32.name = "building_12_4";
 obj_32.transform.localScale = new Vector3(1, 18, 4);
 obj_32.transform.position = new Vector3(-52, 9, -84);
 obj_32.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_32.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_32.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_32.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_32.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_33 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_33.name = "building_12_8";
 obj_33.transform.localScale = new Vector3(3, 19, 4);
 obj_33.transform.position = new Vector3(-52, 10, -68);
 obj_33.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_33.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_33.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_33.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_33.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_34 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_34.name = "building_12_12";
 obj_34.transform.localScale = new Vector3(1, 11, 3);
 obj_34.transform.position = new Vector3(-52, 6, -52);
 obj_34.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_34.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_34.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_34.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_34.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_35 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_35.name = "building_12_16";
 obj_35.transform.localScale = new Vector3(4, 17, 4);
 obj_35.transform.position = new Vector3(-52, 9, -36);
 obj_35.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_35.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_35.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_35.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_35.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_36 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_36.name = "building_12_20";
 obj_36.transform.localScale = new Vector3(1, 13, 3);
 obj_36.transform.position = new Vector3(-52, 7, -20);
 obj_36.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_36.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_36.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_36.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_36.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_37 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_37.name = "building_12_24";
 obj_37.transform.localScale = new Vector3(3, 16, 2);
 obj_37.transform.position = new Vector3(-52, 8, -4);
 obj_37.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_37.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_37.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_37.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_37.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_38 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_38.name = "building_12_28";
 obj_38.transform.localScale = new Vector3(1, 10, 1);
 obj_38.transform.position = new Vector3(-52, 5, 12);
 obj_38.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_38.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_38.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_38.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_38.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_39 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_39.name = "building_12_32";
 obj_39.transform.localScale = new Vector3(2, 15, 3);
 obj_39.transform.position = new Vector3(-52, 8, 28);
 obj_39.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_39.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_39.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_39.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_39.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_40 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_40.name = "building_12_36";
 obj_40.transform.localScale = new Vector3(1, 17, 4);
 obj_40.transform.position = new Vector3(-52, 9, 44);
 obj_40.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_40.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_40.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_40.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_40.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_41 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_41.name = "building_16_0";
 obj_41.transform.localScale = new Vector3(2, 18, 3);
 obj_41.transform.position = new Vector3(-36, 9, -100);
 obj_41.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_41.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_41.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_41.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_41.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_42 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_42.name = "building_16_4";
 obj_42.transform.localScale = new Vector3(4, 19, 2);
 obj_42.transform.position = new Vector3(-36, 10, -84);
 obj_42.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_42.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_42.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_42.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_42.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_43 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_43.name = "building_16_8";
 obj_43.transform.localScale = new Vector3(2, 18, 1);
 obj_43.transform.position = new Vector3(-36, 9, -68);
 obj_43.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_43.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_43.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_43.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_43.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_44 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_44.name = "building_16_12";
 obj_44.transform.localScale = new Vector3(3, 18, 2);
 obj_44.transform.position = new Vector3(-36, 9, -52);
 obj_44.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_44.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_44.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_44.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_44.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_45 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_45.name = "building_16_16";
 obj_45.transform.localScale = new Vector3(2, 15, 1);
 obj_45.transform.position = new Vector3(-36, 8, -36);
 obj_45.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_45.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_45.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_45.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_45.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_46 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_46.name = "building_16_20";
 obj_46.transform.localScale = new Vector3(1, 13, 3);
 obj_46.transform.position = new Vector3(-36, 7, -20);
 obj_46.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_46.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_46.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_46.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_46.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_47 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_47.name = "building_16_24";
 obj_47.transform.localScale = new Vector3(2, 16, 4);
 obj_47.transform.position = new Vector3(-36, 8, -4);
 obj_47.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_47.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_47.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_47.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_47.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_48 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_48.name = "building_16_28";
 obj_48.transform.localScale = new Vector3(4, 19, 1);
 obj_48.transform.position = new Vector3(-36, 10, 12);
 obj_48.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_48.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_48.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_48.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_48.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_49 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_49.name = "building_16_32";
 obj_49.transform.localScale = new Vector3(1, 18, 2);
 obj_49.transform.position = new Vector3(-36, 9, 28);
 obj_49.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_49.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_49.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_49.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_49.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_50 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_50.name = "building_16_36";
 obj_50.transform.localScale = new Vector3(1, 19, 1);
 obj_50.transform.position = new Vector3(-36, 10, 44);
 obj_50.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_50.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_50.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_50.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_50.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_51 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_51.name = "building_20_0";
 obj_51.transform.localScale = new Vector3(1, 16, 1);
 obj_51.transform.position = new Vector3(-20, 8, -100);
 obj_51.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_51.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_51.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_51.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_51.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_52 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_52.name = "building_20_4";
 obj_52.transform.localScale = new Vector3(1, 18, 2);
 obj_52.transform.position = new Vector3(-20, 9, -84);
 obj_52.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_52.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_52.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_52.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_52.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_53 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_53.name = "building_20_8";
 obj_53.transform.localScale = new Vector3(1, 19, 4);
 obj_53.transform.position = new Vector3(-20, 10, -68);
 obj_53.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_53.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_53.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_53.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_53.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_54 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_54.name = "building_20_12";
 obj_54.transform.localScale = new Vector3(3, 18, 3);
 obj_54.transform.position = new Vector3(-20, 9, -52);
 obj_54.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_54.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_54.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_54.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_54.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_55 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_55.name = "building_20_16";
 obj_55.transform.localScale = new Vector3(3, 19, 4);
 obj_55.transform.position = new Vector3(-20, 10, -36);
 obj_55.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_55.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_55.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_55.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_55.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_56 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_56.name = "building_20_20";
 obj_56.transform.localScale = new Vector3(4, 15, 2);
 obj_56.transform.position = new Vector3(-20, 8, -20);
 obj_56.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_56.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_56.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_56.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_56.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_57 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_57.name = "building_20_24";
 obj_57.transform.localScale = new Vector3(1, 12, 2);
 obj_57.transform.position = new Vector3(-20, 6, -4);
 obj_57.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_57.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_57.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_57.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_57.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_58 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_58.name = "building_20_28";
 obj_58.transform.localScale = new Vector3(4, 16, 1);
 obj_58.transform.position = new Vector3(-20, 8, 12);
 obj_58.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_58.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_58.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_58.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_58.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_59 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_59.name = "building_20_32";
 obj_59.transform.localScale = new Vector3(1, 13, 4);
 obj_59.transform.position = new Vector3(-20, 7, 28);
 obj_59.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_59.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_59.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_59.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_59.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_60 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_60.name = "building_20_36";
 obj_60.transform.localScale = new Vector3(2, 18, 1);
 obj_60.transform.position = new Vector3(-20, 9, 44);
 obj_60.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_60.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_60.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_60.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_60.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_61 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_61.name = "building_24_0";
 obj_61.transform.localScale = new Vector3(4, 12, 4);
 obj_61.transform.position = new Vector3(-4, 6, -100);
 obj_61.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_61.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_61.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_61.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_61.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_62 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_62.name = "building_24_4";
 obj_62.transform.localScale = new Vector3(4, 14, 1);
 obj_62.transform.position = new Vector3(-4, 7, -84);
 obj_62.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_62.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_62.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_62.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_62.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_63 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_63.name = "building_24_8";
 obj_63.transform.localScale = new Vector3(2, 13, 3);
 obj_63.transform.position = new Vector3(-4, 7, -68);
 obj_63.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_63.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_63.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_63.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_63.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_64 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_64.name = "building_24_12";
 obj_64.transform.localScale = new Vector3(4, 19, 2);
 obj_64.transform.position = new Vector3(-4, 10, -52);
 obj_64.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_64.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_64.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_64.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_64.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_65 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_65.name = "building_24_16";
 obj_65.transform.localScale = new Vector3(4, 18, 4);
 obj_65.transform.position = new Vector3(-4, 9, -36);
 obj_65.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_65.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_65.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_65.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_65.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_66 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_66.name = "building_24_20";
 obj_66.transform.localScale = new Vector3(2, 14, 1);
 obj_66.transform.position = new Vector3(-4, 7, -20);
 obj_66.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_66.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_66.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_66.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_66.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_67 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_67.name = "building_24_24";
 obj_67.transform.localScale = new Vector3(2, 11, 2);
 obj_67.transform.position = new Vector3(-4, 6, -4);
 obj_67.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_67.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_67.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_67.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_67.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_68 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_68.name = "building_24_28";
 obj_68.transform.localScale = new Vector3(4, 19, 3);
 obj_68.transform.position = new Vector3(-4, 10, 12);
 obj_68.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_68.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_68.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_68.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_68.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_69 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_69.name = "building_24_32";
 obj_69.transform.localScale = new Vector3(4, 13, 4);
 obj_69.transform.position = new Vector3(-4, 7, 28);
 obj_69.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_69.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_69.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_69.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_69.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_70 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_70.name = "building_24_36";
 obj_70.transform.localScale = new Vector3(1, 11, 3);
 obj_70.transform.position = new Vector3(-4, 6, 44);
 obj_70.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_70.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_70.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_70.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_70.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_71 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_71.name = "building_28_0";
 obj_71.transform.localScale = new Vector3(3, 16, 1);
 obj_71.transform.position = new Vector3(12, 8, -100);
 obj_71.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_71.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_71.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_71.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_71.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_72 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_72.name = "building_28_4";
 obj_72.transform.localScale = new Vector3(3, 15, 3);
 obj_72.transform.position = new Vector3(12, 8, -84);
 obj_72.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_72.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_72.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_72.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_72.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_73 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_73.name = "building_28_8";
 obj_73.transform.localScale = new Vector3(3, 17, 3);
 obj_73.transform.position = new Vector3(12, 9, -68);
 obj_73.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_73.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_73.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_73.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_73.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_74 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_74.name = "building_28_12";
 obj_74.transform.localScale = new Vector3(3, 16, 1);
 obj_74.transform.position = new Vector3(12, 8, -52);
 obj_74.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_74.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_74.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_74.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_74.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_75 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_75.name = "building_28_16";
 obj_75.transform.localScale = new Vector3(4, 13, 2);
 obj_75.transform.position = new Vector3(12, 7, -36);
 obj_75.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_75.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_75.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_75.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_75.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_76 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_76.name = "building_28_20";
 obj_76.transform.localScale = new Vector3(4, 19, 4);
 obj_76.transform.position = new Vector3(12, 10, -20);
 obj_76.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_76.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_76.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_76.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_76.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_77 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_77.name = "building_28_24";
 obj_77.transform.localScale = new Vector3(1, 17, 4);
 obj_77.transform.position = new Vector3(12, 9, -4);
 obj_77.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_77.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_77.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_77.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_77.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_78 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_78.name = "building_28_28";
 obj_78.transform.localScale = new Vector3(4, 10, 3);
 obj_78.transform.position = new Vector3(12, 5, 12);
 obj_78.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_78.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_78.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_78.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_78.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_79 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_79.name = "building_28_32";
 obj_79.transform.localScale = new Vector3(3, 10, 2);
 obj_79.transform.position = new Vector3(12, 5, 28);
 obj_79.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_79.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_79.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_79.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_79.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_80 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_80.name = "building_28_36";
 obj_80.transform.localScale = new Vector3(1, 18, 1);
 obj_80.transform.position = new Vector3(12, 9, 44);
 obj_80.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_80.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_80.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_80.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_80.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_81 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_81.name = "building_32_0";
 obj_81.transform.localScale = new Vector3(1, 11, 2);
 obj_81.transform.position = new Vector3(28, 6, -100);
 obj_81.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_81.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_81.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_81.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_81.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_82 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_82.name = "building_32_4";
 obj_82.transform.localScale = new Vector3(1, 12, 2);
 obj_82.transform.position = new Vector3(28, 6, -84);
 obj_82.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_82.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_82.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_82.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_82.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_83 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_83.name = "building_32_8";
 obj_83.transform.localScale = new Vector3(1, 11, 2);
 obj_83.transform.position = new Vector3(28, 6, -68);
 obj_83.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_83.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_83.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_83.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_83.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_84 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_84.name = "building_32_12";
 obj_84.transform.localScale = new Vector3(1, 16, 3);
 obj_84.transform.position = new Vector3(28, 8, -52);
 obj_84.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_84.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_84.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_84.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_84.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_85 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_85.name = "building_32_16";
 obj_85.transform.localScale = new Vector3(3, 17, 2);
 obj_85.transform.position = new Vector3(28, 9, -36);
 obj_85.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_85.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_85.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_85.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_85.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_86 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_86.name = "building_32_20";
 obj_86.transform.localScale = new Vector3(1, 11, 3);
 obj_86.transform.position = new Vector3(28, 6, -20);
 obj_86.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_86.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_86.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_86.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_86.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_87 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_87.name = "building_32_24";
 obj_87.transform.localScale = new Vector3(2, 19, 2);
 obj_87.transform.position = new Vector3(28, 10, -4);
 obj_87.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_87.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_87.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_87.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_87.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_88 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_88.name = "building_32_28";
 obj_88.transform.localScale = new Vector3(1, 18, 2);
 obj_88.transform.position = new Vector3(28, 9, 12);
 obj_88.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_88.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_88.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_88.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_88.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_89 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_89.name = "building_32_32";
 obj_89.transform.localScale = new Vector3(3, 16, 3);
 obj_89.transform.position = new Vector3(28, 8, 28);
 obj_89.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_89.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_89.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_89.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_89.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_90 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_90.name = "building_32_36";
 obj_90.transform.localScale = new Vector3(2, 10, 2);
 obj_90.transform.position = new Vector3(28, 5, 44);
 obj_90.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_90.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_90.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_90.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_90.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_91 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_91.name = "building_36_0";
 obj_91.transform.localScale = new Vector3(2, 15, 4);
 obj_91.transform.position = new Vector3(44, 8, -100);
 obj_91.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_91.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_91.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_91.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_91.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_92 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_92.name = "building_36_4";
 obj_92.transform.localScale = new Vector3(2, 14, 3);
 obj_92.transform.position = new Vector3(44, 7, -84);
 obj_92.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_92.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_92.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_92.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_92.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_93 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_93.name = "building_36_8";
 obj_93.transform.localScale = new Vector3(4, 15, 1);
 obj_93.transform.position = new Vector3(44, 8, -68);
 obj_93.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_93.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_93.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_93.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_93.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_94 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_94.name = "building_36_12";
 obj_94.transform.localScale = new Vector3(1, 17, 4);
 obj_94.transform.position = new Vector3(44, 9, -52);
 obj_94.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_94.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_94.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_94.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_94.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_95 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_95.name = "building_36_16";
 obj_95.transform.localScale = new Vector3(2, 10, 1);
 obj_95.transform.position = new Vector3(44, 5, -36);
 obj_95.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_95.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_95.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_95.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_95.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_96 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_96.name = "building_36_20";
 obj_96.transform.localScale = new Vector3(2, 13, 2);
 obj_96.transform.position = new Vector3(44, 7, -20);
 obj_96.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_96.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_96.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_96.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_96.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_97 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_97.name = "building_36_24";
 obj_97.transform.localScale = new Vector3(1, 14, 4);
 obj_97.transform.position = new Vector3(44, 7, -4);
 obj_97.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_97.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_97.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_97.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_97.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_98 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_98.name = "building_36_28";
 obj_98.transform.localScale = new Vector3(3, 18, 4);
 obj_98.transform.position = new Vector3(44, 9, 12);
 obj_98.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_98.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_98.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_98.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_98.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_99 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_99.name = "building_36_32";
 obj_99.transform.localScale = new Vector3(4, 19, 2);
 obj_99.transform.position = new Vector3(44, 10, 28);
 obj_99.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_99.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_99.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_99.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_99.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_100 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_100.name = "building_36_36";
 obj_100.transform.localScale = new Vector3(4, 16, 3);
 obj_100.transform.position = new Vector3(44, 8, 44);
 obj_100.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_100.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("building_diffuse"));
 obj_100.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_100.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("building_normal"));
 obj_100.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_101 = GameObject.CreatePrimitive(PrimitiveType.Cube);
 obj_101.name = "Landmark";
 obj_101.transform.localScale = new Vector3(5, 50, 5);
 obj_101.transform.position = new Vector3(0, 25, 0);
 obj_101.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_101.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("landmark_diffuse"));
 obj_101.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(3, 10));
 obj_101.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("landmark_normal"));
 obj_101.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(3, 10));
GameObject obj_102 = GameObject.CreatePrimitive(PrimitiveType.Plane);
 obj_102.name = "park";
 obj_102.transform.localScale = new Vector3(10, 10, 10);
 obj_102.transform.position = new Vector3(100, 1, 0);
 obj_102.GetComponent<Renderer>().material.EnableKeyword("_NORMALMAP");
 obj_102.GetComponent<Renderer>().material.SetTexture("_MainTex", Resources.Load<Texture2D>("grass_diffuse"));
 obj_102.GetComponent<Renderer>().material.SetTextureScale("_MainTex", new Vector3(10, 10));
 obj_102.GetComponent<Renderer>().material.SetTexture("_BumpMap", Resources.Load<Texture2D>("grass_normal"));
 obj_102.GetComponent<Renderer>().material.SetTextureScale("_BumpMap", new Vector3(10, 10));
}}
